version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    # depends_on:
    #   - minio
    network_mode: host
    environment:
      - MINIO_URL=192.168.29.128:9000
      # - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=""
      - MINIO_SECRET_KEY=""
    # networks:
    #   - my-network

  # minio:
  #   image: quay.io/minio/minio:latest
  #   container_name: minio
  #   environment:
  #     - MINIO_ROOT_USER=ROOTNAME
  #     - MINIO_ROOT_PASSWORD=CHANGEME123
  #     - MINIO_ACCESS_KEY=""
  #     - MINIO_SECRET_KEY=""
  #   ports:
  #     - "9000:9000"   # Minio API
  #     - "9001:9001"   # Minio Console
  #   volumes:
  #     - ~/minio/data:/data  # Persistent storage
  #   command: server /data --console-address ":9001"
  #   networks:
  #     - my-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  minio-data:
